name: DevSecOps Pipeline - Secured

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  security-events: write

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    # SAST - CodeQL
    - name: Init CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: python

    - name: Analyze with CodeQL
      uses: github/codeql-action/analyze@v3

    # Analyse sécurité Python
    - name: Install Bandit
      run: pip install bandit

    - name: Run Bandit
      run: bandit -r api -ll

    # Scan dépendances sécurisées
    - name: Install Safety
      run: pip install safety

    - name: Run Safety
      run: safety check -r requirements.txt

    # Build image Docker durcie
    - name: Build Docker Image
      run: docker build -t devsecops-app .

    # Scan image Docker 
    - name: Trivy Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: devsecops-app
        severity: CRITICAL,HIGH
        exit-code: 1
